### ISSUE TITLE
Automatically Closing Tags?

### ISSUE THREAD

**Issue by mbuttler** [Hebilicious/gatsby-remark-component#12]
Hello!

I'm noticing an issue when I try to use automatically closing tags.

For example, when I build using this in my markdown file:
`<component-one /> <component-two />`

I can only get `component-one` to display:

![image](https://user-images.githubusercontent.com/3672022/43781108-261345b4-9a2a-11e8-82bf-941f93596e06.png)

When I explicitly open and close the components, they work fine and dandy.

For example:
`<component-one></component-one><component-two></component-two>`

![image](https://user-images.githubusercontent.com/3672022/43781214-682acd1e-9a2a-11e8-8eca-b71de206b2e1.png)

**Comment by cupojoe** [comment]
Yeah, it is a requirement otherwise they get stripped out by remark
