### ISSUE TITLE
Cannot pass props to component

### ISSUE THREAD

**Issue by pdnellius** [Hebilicious/gatsby-remark-component#14]
I'm unable to pass a prop from the parent component to the child component rendered using `rehype-react`. For instance, I'd like to pass the `fileAbsolutePath` of a node to the rendered component so that I can use it in an image gallery. The image would live within the same folder as the post that I am creating (parallel to the `index.md`). In order to do this, I need to be able to pass the directory location to the component that gets rendered.

Is this possible? If not, is there a way to work around this?

**Comment by macandcheese** [comment]
@pdnellius I had the same need... to basically pass the asset hashed and absolutely located path of the final built asset as a prop to the component... I ended up modifying [gatsby-remark-copy-linked-files at this line](https://github.com/gatsbyjs/gatsby/blob/ad5132a367b695e0f2025d463a79348a3e9af1f0/packages/gatsby-remark-copy-linked-files/src/index.js#L271) with the component name and prop I wanted to pass. Would be cleaner to move to the plugin configuration section but it works to pass the desired hashed prop in a pinch.

**Comment by rstacruz** [comment]
hey I was just curious - what's your use case for. Gatsby-remark-component?

I just learned that instead of doing:

```html
<my-component></my-component>
```

you can simply write it with a div wrapper:

```html
<div>
<my-component></mygcomponent>
</div>
```

... which will do the same thing as this plugin :)

**Comment by AlbertWhite** [comment]
The prop doesn't support uppercase. It is a bug.
