### ISSUE TITLE
Unable to find components in specific circumstances

### ISSUE THREAD

**Issue by baobabKoodaa** [Hebilicious/gatsby-remark-component#16]
I have a custom component that takes props.

This works great when I apply it to all components like this:

```
plugins: [
  {
    resolve: "gatsby-transformer-remark",
    options: {
      plugins: ["gatsby-remark-component"]
    }
  }
]
```

But it doesn't work at all when I select components: 

```
plugins: [
  {
    resolve: "gatsby-transformer-remark",
    options: {
      plugins: [
        {
          resolve: "gatsby-remark-component",
          options: { components: ["my-component", "other-component"] }
        }
      ]
    }
  }
]
```

It doesn't give any errors, it doesn't log any "found component..." in console anymore, and it just doesn't replace the div tag.

Edit: turns out this issue occurs only when a custom component takes props.

**Comment by baobabKoodaa** [comment]
I decided to fork this since it's not being maintained otherwise: https://github.com/baobabkoodaa/gatsby-remark-component-parent2div

**Comment by rstacruz** [comment]
Hey there, I'm maintaining my own fork at http://github.com/rstacruz/gatsby-remark-component.

Can I merge your changes in?

**Comment by baobabKoodaa** [comment]
> Hey there, I'm maintaining my own fork at [http://github.com/rstacruz/gatsby-remark-component](https://github.com/rstacruz/gatsby-remark-component).
> 
> Can I merge your changes in, or can I invite you to make your PR there?

Sure! It looks like your changes are mainly related to build tools and my changes are mainly in `index.js` so merging should be easy. I'll send an untested PR.

**Comment by rstacruz** [comment]
hey I was just curious - what's your use case for. Gatsby-remark-component?

I just learned that instead of doing:

```html
<my-component></my-component>
```

you can simply write it with a div wrapper:

```html
<div>
<my-component></mygcomponent>
</div>
```

... which will do the same thing as this plugin :)

**Comment by baobabKoodaa** [comment]
> hey I was just curious - what's your use case for. Gatsby-remark-component?
> 
> I just learned that instead of doing:
> 
> ```
> <my-component></my-component>
> ```
> 
> you can simply write it with a div wrapper:
> 
> ```
> <div>
> <my-component></mygcomponent>
> </div>
> ```
> 
> ... which will do the same thing as this plugin :)

Do you mean that giving a `<div>` wrapper to a custom component in Markdown will cause `gatsby-transform-remark` to replace the parent `<p>` tag with `<div>`? I would have expected it to simply nest a `<div>` inside `<p>`. Let me know if you still want the PR.
