### ISSUE TITLE
Thinks regular HTML elements are custom tags

### ISSUE THREAD

**Issue by designbyadrian** [Hebilicious/gatsby-remark-component#2]
I get this output in the console:

```
Found a custom tag <a href="http://domain">
Found a custom tag </a>
```

The entire paragraph is replaced by a DIV. All I had in the markdown was this:

`After two iterations and Google Analytics inspections with <a href="http://domain.com">Name Name</a>`

I assume this is the important part of my gatsby-config:

```
'gatsby-plugin-react-next',
{
    resolve: 'gatsby-source-contentful',
    options: {
      spaceId: 'xyzy',
      accessToken: '123',
    },
  },
  {
  resolve: "gatsby-transformer-remark",
    options: {
      plugins: ["gatsby-remark-component"]
    }
  }
```

**Comment by designbyadrian** [comment]
I've created a PM for you:

https://github.com/Hebilicious/gatsby-remark-component/pull/3

**Comment by Hebilicious** [comment]
Nice catch thanks! I'll merge that in soon.
