### ISSUE TITLE
Not working with some tag-names

### ISSUE THREAD

**Issue by marko-invision** [Hebilicious/gatsby-remark-component#4]
Hey,
i think there is a bug. When I am using something like `<component></component>` the parent container updates to div to prevent invalid dom nesting. Nice.

But this does not update if the tag name is somthing like `<atest></atest>` or `<a-test></a-test>` or `<ipsum></ipsum>`. `<cccatest></cccatest>` is working!

My assumption: If a Tag-Name starts with a letter from a valid html tag name the override is not triggering.  Maybe there is something breaks the mechanism, if the tag-name begins like an valid html tag name? I mean `<i>` like `<ipsum>` and `<a>` tag like `<atest>` ? So maybe the check is not the best solution?
`     
 if (!html.some(tag => node.value.startsWith(`<${tag}`) || node.value.startsWith(`</${tag}`))) {
`
in https://github.com/Hebilicious/gatsby-remark-component/blob/master/src/index.js#L27

Or did i something wrong?

**Comment by Hebilicious** [comment]
Hey, I merged that from a recent pull request, but didn't think of that. I'm working on a more robust regex solution.

**Comment by Hebilicious** [comment]
The latest commit should fix the issue. I upgrade the package on npm also, let me know if you have more issues.

**Comment by marko-invision** [comment]
Super fast fix! Thank you.
