### ISSUE TITLE
Found a custom tag... what should I do?

### ISSUE THREAD

**Issue by docwhat** [Hebilicious/gatsby-remark-component#6]
I pulled in a large amount of Markdown files [into my site](https://github.com/docwhat/docwhat) and when I run `gatsby develop` or `build` I get a huge amount of output about "Found a custom tag".

I realize some are bogus (e.g. `<narf>`) but others seem to be legit (e.g. comments, `</a>`, lines with multiple tags).

- What am I supposed to do?
- What files are these problems in? (I can guess some)
- What line number is a problem on?
- If they are harmless, can I turn them off?

Here's an example of the output:

```
Found a custom tag <narf>
Wow!  I found a blog post talking about <a href="http://addons.mozilla.org/firefox/4125">It's All Text!</a> on a blog called <a href="http://d.hatena.ne.jp/nyama/">Another 朝顔日記</a> written in <a href="http://technorati.com/tag/japanese" rel="tag">japanese</a>!
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag </code>
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag </narf>

Found a custom tag <!-- ckey="3406B841" -->
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag <!--more-->
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag <pre>Harm:      2.7
Fairness:  2.3
Loyalty:   1.5
Authority: 1.0
Purity:    0.7</pre>

Found a custom tag </a>
Found a custom tag </a>
Found a custom tag <pre> US      JP
 :-)     ^_^
 x-)      &gt;_&lt;
 :-(     ;_;</pre>

Found a custom tag <tt>
Found a custom tag </tt>
Found a custom tag <!--nevermore-->

Found a custom tag <narf>
So I have finally submitted It's All Text! to <a href="http://www.babelzilla.org/">Babelzilla</a>, the mozilla translation site.  It took a little <a href="http://www.babelzilla.org/forum/index.php?showtopic=3269&amp;st=0&amp;p=30125&amp;#entry30125">work</a> to get in, though.  There isn't anything so simple that I cannot break it. :-)
Found a custom tag <!--more-->
Found a custom tag </a>
Found a custom tag </a>
Found a custom tag </a>
```

**Comment by meechanism** [comment]
I'd also like to turn off the logs for `Found a custom tag`. It happens to be extremely verbose in our app. :(

The `console.log` is in the `setParentForNonHtmlElements()` method in the src: https://github.com/Hebilicious/gatsby-remark-component/blob/master/src/index.js

**Comment by cupojoe** [comment]
@Hebilicious The PR #7 was merged by this was never built or published to npm. Any way you could either of those things, or both?

**Comment by afc163** [comment]
+1
