### ISSUE TITLE
validateDOMNesting warning

### ISSUE THREAD

**Issue by anandrikka** [Hebilicious/gatsby-remark-component#9]
Hi I followed the same steps mentioned in [https://using-remark.gatsbyjs.org/custom-components/#writing-a-component](https://using-remark.gatsbyjs.org/custom-components/#writing-a-component) but I'm getting validateDOMNesting warning in console

I'm using following version of plugins:
 "gatsby-remark-component": "^1.1.3",
"gatsby-transformer-remark": "^1.7.42"

**Comment by creativeaura** [comment]
try using a span tag instead of div tag. If you are using a div tag transformation will try to include your div tag inside a p tag.
